### PR TITLE
RPC ledger, accounts_create, block_create (offline signing), wallet_lock

### PR DESCRIPTION
**Pull request by SergiySW**
https://github.com/clemahieu/raiblocks/issues/183
RPC wallet_balances optional threshold
RPC representatives optional sorting
RPC process should return new block hash
RPC stop should return success

RPC wallet_lock to lock wallet
RPC wallet_unlock (alias to password_enter), wallet_locked (alias to password_valid)

Allow generate accounts without work
Allow generate blocks with external work (https://github.com/clemahieu/raiblocks/issues/95)

### CODE REVIEW

**Comment by nylazormalaca** [comment]
Sir can you.explain.old acct that cannot reach th in 2 weeks will be
reset.why no notification for claimers hows terrible was that?

**Comment by SergiySW** [comment]
Allow generate accounts without work
Allow generate blocks with external work

**Comment by SergiySW** [comment]
https://github.com/clemahieu/raiblocks/pull/184

**Comment by clemahieu** [comment]
Merged in 307ae804205e2dcb31dcfccbed3ad82bcf58ed37

**Pull request closed without merging**
