### PR TITLE
Readme update feb 2018

### PR DESCRIPTION
**Pull request by cryptocode**
RaiBlocks -> Nano, link updates and more resources.

Would be nice to update the unpruned ledger size info too (anyone got exact size?)

Preview: https://github.com/cryptocode/raiblocks/tree/readme-update-feb-2018

### CODE REVIEW

**Comment by polyzen** [comment]
I love this rebrand.

**Comment by stefonarch** [comment]
> Would be nice to update the unpruned ledger size info too (anyone got exact size?)

if you   with "unpruned" mean never run --vacuum: I downloaded a presynced ledger days ago from google driver, now it is
`1.9G Feb  6 13:32 data.ldb
`

**Comment by cryptocode** [comment]
@stefonarch nah, pruning and vacuuming are different things.

**Comment by stefonarch** [comment]
Maybe both values?

**Comment by androm3da** [comment]
LGTM

**Pull request merged**
