### PR TITLE
Improved python code in bootstrap.py

### PR DESCRIPTION
**Pull request by citizen2077**
Changed file opens to "with open()"s, https://stackoverflow.com/questions/31334061/file-read-using-open-vs-with-open

Changed string concatenation from + to "".join() because it's faster for 3 elements

Changed use of a counter variable "block_number" and 3 conversions to string to enumerate() and one conversion to string

Should still work just the same as it did before, even if using Python 2.7 upward

Double check it still works though please

### CODE REVIEW

**Comment by androm3da** [comment]
Please squash these commits.

**Comment by citizen2077** [comment]
@androm3da Sure, is this something I can do or? I don't know how. I could remove the pull request and create a new succinct one instead?

**Comment by androm3da** [comment]
Rebase the local branch then force push to this branch.

**Comment by citizen2077** [comment]
@androm3da Sorry, I am just using the website and I've looked around for help but it is not clear to me how to do what you're describing, I am new to github collaboration.

**Comment by citizen2077** [comment]
@NicholasKobald Thank you for your help, by "on your local branch" which branch do you mean? do I clone a repository? and which one do I clone; the forked raiblocks on my profile or clemahieus raiblocks? I can't see the commits on my repository, only on the pull request on clemahieus

**Pull request merged**
