### PR TITLE
RPC support for listing all wallets in a node

### PR DESCRIPTION
**Pull request by brightmonkey**
In the process of investigating issue #458, I discovered there isn't a simple way to see what wallets a node actually contains. 

So, I added an RPC command named "wallet_list" that lists all wallets controlled by the node. The output looks like this:

mariog$ curl -g -d '{ "action": "wallet_list"}' '[::1]:7076'
{
    "wallets": [
        "D4F5829253E41DCC3AAECF9DE1142AD052BBCCD9F5E4F101D88A8EFE6D3850F6",
        "B04E7807B3F23EC28ECA579DF25A39925815E97078388701EBDC67DF2F1C12B7",
        "92A806356FAFEEFBCA2454770DA47D15EC1730DA1B10DE4BE7089ECA136195AF"
    ]
}

I also added a test that creates two extra wallets in addition to the default wallet and ensures all of them are listed properly. 

This new command is wrapped with the 'if(rpc.config.enable_control)' flag, since I figured we wouldn't want random Joe Cryptos to be able to query a node for the list of wallets it controls. 

Unfortunately, this commit doesn't _fix_ issue #458, but it should help me with debugging the issue.

### CODE REVIEW

**Comment by PlasmaPower** [comment]
See https://github.com/clemahieu/raiblocks/pull/432

It causes security problems, among other things.

**Comment by brightmonkey** [comment]
Well shucks. Looks like I just reinvented a wheel.

**Comment by PlasmaPower** [comment]
Well, at least you got to know the RaiBlocks codebase a bit better 😄

PM me on Discord if you want any help with this issue: PlasmaPower#0068

**Comment by brightmonkey** [comment]
Yes, the one benefit of reinventing a wheel is that you end up understanding the wheel very well 😂

On Feb 1, 2018, at 9:29 PM, Lee Bousfield <notifications@github.com> wrote:

Well, at least you got to know the RaiBlocks codebase a bit better 😄

PM me on Discord if you want any help with this issue: PlasmaPower#0068

**Comment by brightmonkey** [comment]
Looks like the Travis build failed because I didn't run clang-format first. Oops. Regardless, I'm going to close this pull request in light of the new information.

**Comment by brightmonkey** [comment]
As per comments in #432, it's clear this feature should not be in any release implementation of a node. But thinking about this some more, there's definitely value in being able to query nodes for a wallet list for debug purposes only.  @clemahieu, what are your thoughts on adding this functionality under a special debug flag?

**Comment by brightmonkey** [comment]
On second thought, forget what I said about adding it under a debug flag. Regardless of how much of a barrier we add, someone somewhere will inevitably deploy it by mistake with potential bad consequences. I'll just keep this patch tucked away and apply it locally when I need it.

**Comment by cryptocode** [comment]
@brightmonkey and for debug needs, you can always use `--wallet_list` on the node

**Comment by brightmonkey** [comment]
@cryptocode true, but I'd have to stop the node in order to use that option. Issue #458 refers to a situation where a node is already running, which is why I needed a way to query it in real time.

**Comment by cryptocode** [comment]
Yeah, that's an issue ;)

**Pull request closed without merging**
