### PR TITLE
Support wallet_list in RPC

### PR DESCRIPTION
**Pull request by cryptocode**
Implements `wallet_list` in RPC.

See https://github.com/clemahieu/raiblocks/issues/430

### CODE REVIEW

**Comment by cryptocode** [comment]
@androm3da Test case added

**Comment by androm3da** [comment]
@clemahieu any reason not to disclose the wallet IDs to the RPC peer?  Sounds like a reasonable request from #430 and RPC seems like it's designed to be trusted.

**Comment by clemahieu** [comment]
The only reason I haven't added this is as a layer of security, basically the wallet IDs serve as an API key.  Right now even if someone gets access to an exposed RPC port they would need the wallet IDs to actually make transactions.

The only current way to get the wallet ids is on the command line, with this they could get it through the RPC system.

**Comment by cryptocode** [comment]
@clemahieu So either add a config flag, or ditch this PR? I'm fine with both :)

**Comment by PlasmaPower** [comment]
Be careful with this - CORS is enabled for the RPC. That means if you have rai_node running locally, and wallet_list enabled, any website you visit in your browser can steal your XRB.

**Comment by clemahieu** [comment]
Yea I think we have to deal with the inconvenience for now until we get better security on the RPC port.  If we had a mapping of certificate -> wallet ID and could validate with https that would be ideal but it's only http at the moment.

**Comment by cryptocode** [comment]
@PlasmaPower right, the eth guys are having this problem. Closing.

**Pull request closed without merging**
