### PR TITLE
Add .travis.yml

### PR DESCRIPTION
**Pull request by drizzt**
TODO:
 - Fix and enable OSX build support
 - Enable Windows (mingw) build support

### CODE REVIEW

**Comment by drizzt** [comment]
You still need to enable travis and caching support on https://travis-ci.org

**Comment by androm3da** [comment]
Does it actually work?  When I tested building raiblocks on travis I found that the builds would all fail because of resource limits.  I added gitlab CI instead.  

Travis is great if it works.

**Comment by drizzt** [comment]
I had to change slightly the commit since plain "make" is actually broken due to broken qt_test as you can see in [the log](https://api.travis-ci.org/v3/job/324171995/log.txt) and so I changed the travis script to only use `make rai_node rai_wallet`.

I think think should be changed when qt_test is fixed since plain make should always work.

Example of working travis job: https://travis-ci.org/drizzt/raiblockscommunity/builds/324215243

**Comment by lukealonso** [comment]
We should make a docker image with boost and the other dependencies already installed, but this is a great first step.

**Comment by androm3da** [comment]
I'll bet I had trouble because I used ninja and it was spawning too many parallel processes. 

Can you adapt CI/build.sh to use unix makefiles and invoke it here?

**Comment by androm3da** [comment]
Let's make and run the full test suite but have it contingent on the other PR already queued that fixes qt_test

**Comment by androm3da** [comment]
The mingw build would use a cross compiler?  Could you really make executables too?   Is there a linker that you can use on linux that makes COFF binaries?

**Comment by neilsh** [comment]
For reference, here's the other PR that fixes qt_test: https://github.com/clemahieu/raiblocks/pull/369

**Comment by lukealonso** [comment]
@androm3da we could make binaries with some other CI, as long as this is running tests for us per-PR

**Comment by androm3da** [comment]
yes that's fine

**Comment by androm3da** [comment]
Now that #369 is merged please include the full scope

**Comment by androm3da** [comment]
@clemahieu to follow through we need to enable this in travis: http://travis-ci.org/clemahieu/

**Pull request merged**
